# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self


trigger:
  branches:
    include:
    - main
    - features/*
  paths:
    include:
    - ./*
    exclude:
    - README.md    


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: BuildStrapi
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'
    steps:          
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: russellstather/encrypxon.dev2fa
        dockerfile: '**/./Dockerfile'
        containerRegistry: dockerhub
        buildContext: '.'
        tags: |
            $(tag) 
    - task: PublishPipelineArtifact@0
      inputs:
        targetPath: '$(Build.SourcesDirectory)/docuapi/docker-compose.yml'
        artifactName: dockercompose


- stage: DeployToDev
  displayName: Deploy to Dev
  dependsOn: Build
  jobs:
  - deployment: Deploy    
    displayName: Deploying to Development
    pool:
        vmImage: 'ubuntu-latest'
    environment: 'dev'
    strategy:
       runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(Pipeline.Workspace)'
              artifactName: 'dockercompose'
          - task: CmdLine@2
            inputs:
              script: ls -a 
              workingDirectory: $(System.DefaultWorkingDirectory)
          - task: DockerCompose@0
            displayName: Pull images
            continueOnError: true
            inputs:
              action: 'Run a docker compose command'
              buildImages: false
              dockerHostEndpoint: 'encrypxonhost1dockerhost'
              containerregistrytype: 'Container Registry'
              dockerRegistryServiceConnection: 'dockerhub'
              dockerComposeFile: '../docker-compose.yml'
              dockerComposeFileArgs:  |
                BUILD_ID=$(Build.BuildId)
              qualifyImageNames: false
              dockerComposeCommand: pull web
          - task: DockerCompose@0
            displayName: Deploy using docker compose
            continueOnError: true
            inputs:
              action: 'Run a docker compose command'
              buildImages: false
              dockerHostEndpoint: 'encrypxonhost1dockerhost'
              containerRegistryType: 'Container Registry'
              dockerRegistryServiceConnection: 'dockerhub'
              dockerComposeFile: '../docker-compose.yml'
              dockerComposeFileArgs: |
                BUILD_ID=$(Build.BuildId)
              qualifyImageNames: false
              dockerComposeCommand: up -d --force-recreate web


#
                

