theme = "docuapi"
themesdir = "../.."
languageCode = "en-us"
baseurl = "https://docuapi.netlify.com/"
title = "DocuAPI Example Site"

disableKinds = ["taxonomyTerm"]

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

defaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"
    [markup.goldmark.renderer]
        unsafe = true

[module]
[module.hugoVersion]
[[module.imports]]
# We include the theme by "../.." above, but we need one module import for Hugo to detect us as a Hugo Module.
path="github.com/bep/empty-hugo-module"

[params]
search = true
maxMenuDepth = 3 # (optional) available options are: 1, 2, or 3 (default: 2)
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "csharp"
name = "CSharp" 
[[params.language_tabs]]
key = "shell"
name = "Shell" 
[[params.language_tabs]]
key = "javascript"
name = "Javascript"

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "DocuAPI Example Site"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='mailto:info@encrypxon.com'>Sign Up for a Developer Key</a>",
"Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme by [bep](https://github.com/bep)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true



